### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Chiinami** [GandaG/fomod-validator#7] opened 2019-06-24 14:30 UTC
Hello ! I have a problem with creating a fomod.... I wanted to check with your program but I have this error message:

Error information:

Version: 2.2.2
<class 'lxml.etree.XMLSyntaxError'>: xmlParseEntityRef: no name, line 114, column 46 (file:/C:/Users/Zorro/Desktop/Traductions%20Maison/Magical%20College%20of%20Winterhold/SSE/fomod/moduleconfig.xml, line 114)

  File "fomod_validator.py", line 259, in button_validate_clicked
  File "site-packages\pyfomod\parser.py", line 244, in parse
  File "site-packages\pyfomod\parser.py", line 203, in _iterparse
  File "src\lxml\iterparse.pxi", line 209, in lxml.etree.iterparse.__next__
  File "src\lxml\iterparse.pxi", line 194, in lxml.etree.iterparse.__next__
  File "src\lxml\iterparse.pxi", line 229, in lxml.etree.iterparse._read_more_events
  File "src\lxml\parser.pxi", line 1364, in lxml.etree._FeedParser.feed
  File "src\lxml\parser.pxi", line 592, in lxml.etree._ParserContext._handleParseResult
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError

I use the version 2.2.2, Thanks !

**Comment by GandaG** [comment] 2019-06-30 16:24
> `XMLSyntaxError`

This probably means the xml itself is incorrect (the syntax), nothing to do with the fomod - but I should also account for this. Just to make sure, can you post the xml (or a pastebin link) up to line 114?

**Comment by GandaG** [comment] 2019-08-19 16:20
This should already be handled by pyfomod. Closing due to lack of information, feel free to reopen to provide the xml that is throwing the exception.

**Closed by GandaG** 2019-08-19 16:20 UTC
Labels: bug

**Comment by Chiinami** [comment] 2019-09-05 09:21
I'm really sorry for the late answer! I found the problem myself: a "&" symbol in the name of one of the folders linked to the installation...

**Comment by GandaG** [comment] 2019-09-05 09:37
Can you post/link the original file? It still shouldn't produce an error
and I can't reproduce it

**Comment by Chiinami** [comment] 2019-09-05 09:45
Do you want the whole mod or just the fomod?

Le jeu. 5 sept. 2019 à 11:37, Daniel Nunes <notifications@github.com> a
écrit :

> Can you post/link the original file? It still shouldn't produce an error
> and I can't reproduce it
>

**Comment by GandaG** [comment] 2019-09-05 13:06
Just the ModuleConfig.xml please

**Comment by Chiinami** [comment] 2019-09-05 13:17
You can download it here: https://mega.nz/#F!2bYDQaZY!ZpAYAElKepeDT6nv_AhRYA

Le jeu. 5 sept. 2019 à 15:06, Daniel Nunes <notifications@github.com> a
écrit :

> Just the ModuleConfig.xml please
>
